name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2  
    - name: Install dependenses structs
      run: go get github.com/fatih/structs
    - name: Install dependenses telegram bot api
      run: go get github.com/go-telegram-bot-api/telegram-bot-api
    - name: Install dependenses mapstructure
      run: go get github.com/mitchellh/mapstructure   
    - name: Build app
      run: go build main.go    
    - name: Copy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        source: "."
        target: "/srv/unix_sect_bot_v2"
        rm: true
    - name: run docker-compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        script: |
          cd /srv/unix_sect_bot_v2
          docker stop $(docker ps -a -q  --filter ancestor=unix_sect_bot_v2_unix_sect_bot)
          docker-compose up -d --build
